Migrating FeesAction getFeeCategoryHeadWise, getDndReport, dltOtherFeesCategory
musaibasrar/Curium pull request #472
Opened 2024-07-24 02:56 UTC by Tauqueer031

2024-07-24 10:37 UTC, reehanlalkhan requested changes

2024-07-24 10:37 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/feescategory/service/FeesService.java
> +	        		searchYear = currentAcademicYearStr.toString();
`searchYear = currentAcademicYearStr;`

2024-07-24 10:37 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/feescategory/action/FeesActionAdapter.java
> +		return studentId;
`return studentIdDto.getStudentId()`

2024-07-24 14:09 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/feescategory/service/FeesService.java
> +	        		searchYear = currentAcademicYearStr.toString();
done

2024-07-24 14:09 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/feescategory/action/FeesActionAdapter.java
> +		return studentId;
done

2024-07-25 03:39 UTC, reehanlalkhan approved these changes

2024-07-25 14:41 UTC, merged