Converted 'AttendanceProcesss' to controller.
musaibasrar/Curium pull request #52
Opened 2021-11-26 07:41 UTC by Adeeba09

2021-11-26 07:43 UTC, Adeeba09 commented
Need suggestion about the method "exportMonthlyAttendanceStaff".

2021-11-28 02:15 UTC, reehanlalkhan requested changes

2021-11-28 02:15 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/attendance/action/AttendanceAction.java
```suggestion
@PostMapping("/exportMonthlyDataStaff")
public String exportMonthlyAttendanceStaff() {
```

2021-11-28 02:31 UTC, reehanlalkhan requested changes
Please press Crtl+Shift+f and Ctrl+Shift+o before pushing changes.

2021-12-10 04:58 UTC, closed without merging