Creating StampFeesApiAction and StampFeesApiActionImpl
musaibasrar/Curium pull request #636
Opened 2024-09-19 03:12 UTC by Tauqueer031

2024-09-19 14:34 UTC, reehanlalkhan requested changes

2024-09-19 14:34 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/stampfees/service/StampFeesService.java
> +		    System.out.println(itemAccount);
Remove the Sysout and replace with log.debug

2024-09-19 14:34 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/stampfees/action/StampFeesApiActionImpl.java
> +		otherFeesDetailsDto.copyOtherFeesCategoryResponseDto(otherFeesCategoryResponseDto);
`otherFeesDetailsDto.setOtherFeecategory(otherFeesCategoryResponseDto.getOtherFeesCategory());`

2024-09-19 14:34 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/stampfees/action/StampFeesApiActionImpl.java
> +		otherFeesDetailsDto.copyResultResponse(result);
`otherFeesDetailsDto.setSuccess(result.isSuccess());`

2024-09-19 14:34 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/stampfees/action/StampFeesActionAdapter.java
> +		searchStudentDto.setSecSearch(request.getParameter("secsearch"));
Here need to set `request.getParameter("academicyear")` also

2024-09-20 03:41 UTC, reehanlalkhan requested changes

2024-09-20 03:41 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/stampfees/service/StampFeesService.java
> +        		//log.debug(ItemLedgerId);
`log.debug("The value of ItemLedgerId:{}", ItemLedgerId);`

2024-09-20 05:17 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/stampfees/action/StampFeesActionAdapter.java
> +		searchStudentDto.setSecSearch(request.getParameter("secsearch"));
done

2024-09-21 13:55 UTC, reehanlalkhan approved these changes

2024-09-23 04:14 UTC, merged