Creating JobApiAction and JobApiActionImpl
musaibasrar/Curium pull request #718
Opened 2024-11-20 12:31 UTC by Tauqueer031

2024-11-20 13:03 UTC, reehanlalkhan requested changes

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/employee/dto/ViewAllEmployeeResponseDto.java
> +import org.ideoholic.curium.model.feescategory.dto.StudentListResponseDto;
No need of this import statement

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/action/JobActionAdapter.java
> +		CombinedQueryDto updateQueriesDto = new CombinedQueryDto();
All these need not be changed

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/service/JobService.java
> +	public SearchStudentResponseDto updateQueryRemarks(CombinedQueryDto combinedQueryDto,String userLoginId ) {
This change is not needed

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/service/JobService.java
> +	public JobQueryDto viewTaskDetails(CombinedQueryDto combinedQueryDto,String branchId) {
This change is not needed

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/dto/EmployeeResponseDto.java
> +public class EmployeeResponseDto {
This needs @JsonInclude(JsonInclude.Include.NON_ABSENT)

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/dto/ViewStudentResponseDto.java
> +@AllArgsConstructor
Need to add @JsonInclude(JsonInclude.Include.NON_ABSENT)

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/dto/ViewStudentResponseDto.java
> +public class ViewStudentResponseDto {
Better name it TaskReportResponseDto

2024-11-20 13:03 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/action/JobApiActionImpl.java
> +
At this point the data from CombinedQueryDto needs to be copied into individual objects of type that can be passed to jobService and viewTaskDetails

2024-11-27 12:21 UTC, reehanlalkhan requested changes

2024-11-27 12:21 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/employee/dto/ViewAllEmployeeResponseDto.java
>  public class ViewAllEmployeeResponseDto {
```suggestion
public class EmployeesWithSalaryResponseDto {
```

2024-11-27 12:21 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/action/JobActionAdapter.java
> +		request.setAttribute("studentList", jobQueryDto.getStudentList());
Remove this line

2024-11-27 12:21 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/job/action/JobActionAdapter.java
> +		request.setAttribute("studentList", jobQueryDto.getTaskList());
Remove this line

2024-11-27 12:45 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/job/action/JobActionAdapter.java
> +		request.setAttribute("studentList", jobQueryDto.getStudentList());
done

2024-11-27 12:48 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/job/action/JobActionAdapter.java
> +		request.setAttribute("studentList", jobQueryDto.getTaskList());
done

2024-11-28 04:00 UTC, reehanlalkhan submitted a review, later dismissed

2024-11-29 03:54 UTC, reehanlalkhan approved these changes

2024-11-29 08:46 UTC, merged