Migrating FeesDetailsAction exportFeesData using Adapter
musaibasrar/Curium pull request #724
Opened 2024-11-26 11:21 UTC by Tauqueer031

2024-11-27 12:22 UTC, reehanlalkhan requested changes

2024-11-27 12:22 UTC, reehanlalkhan commented on src/main/java/org/ideoholic/curium/model/feesdetails/service/FeesDetailsService.java
> +					ResultResponse.builder().success(true).build();
These values are not returned.
It will always return the final false value

2024-11-28 02:35 UTC, Tauqueer031 commented on src/main/java/org/ideoholic/curium/model/feesdetails/service/FeesDetailsService.java
> +					ResultResponse.builder().success(true).build();
This is already done in my code

2024-11-29 04:04 UTC, reehanlalkhan approved these changes

2024-11-29 08:45 UTC, merged